#
# This file is part of the Valdi package.
#
# (c) Philip Lehmann-Böhm <philip@philiplb.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

dist: trusty
language: php
before_script:
    - composer install --dev --prefer-source
script: vendor/bin/phpunit
php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
